### ISSUE TITLE
The CSV Download functionality doesn't work in IE versions 10 and 11

### ISSUE THREAD

**Issue by SachinSunny** [aqeel-legalinc/angular2-json2csv#2]
Hi Aqeel,
This is a great feature. It works fine in Chrome, Firefox, Safari and Edge. But this doesn't work in IE versions. I guess the reason is that IE doesn't support the download attribute for <a> element. Please have a look on this.

**Comment by chuksogbolime** [comment]
Just tested this on IE and it doesn't work.
Error:
HTML7007: One or more blob URLs were revoked by closing the blob for which they were created. These URLs will no longer resolve as the data backing the URL has been freed.

**Comment by aqeel-legalinc** [comment]
@SachinSunny @chuksogbolime The IE issue got fixed, please test it now. I am sure you will not have any issue for this anymore. Thanks!
